'use client';

import Link from 'next/link';
import dynamic from 'next/dynamic';

const LicensePanel = dynamic(() => import('@/app/activate/_components/LicensePanel'), { ssr: false });

export default function LicenseActivatePage() {
  return (
    <div className="min-h-[100svh] bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-50 via-white to-slate-100 dark:from-slate-900 dark:via-slate-950 dark:to-black">
      <div className="mx-auto max-w-5xl px-4 py-10">
        {/* Header */}
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">License & Trial</h1>
            <p className="text-sm text-slate-500 mt-1">
              Start a 7-day trial or activate using a license key. Times shown in IST.
            </p>
          </div>
          <div className="flex gap-2">
            <Link
              href="/activate"
              className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-medium hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"
            >
              OTP Activation
            </Link>
            <Link
              href="/"
              className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-medium hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"
            >
              ← Back to App
            </Link>
          </div>
        </div>

        {/* Panel */}
        <LicensePanel />

        {/* Footer */}
        <div className="mt-10 text-center text-xs text-slate-500 dark:text-slate-400">
          Generated by AxEin Billing
        </div>
      </div>
    </div>
  );
}
